var nombre = prompt('HOLA!¿Cómo te llamas?')
var estilo = prompt('¿Qué estilo prefieres entre clasico/deportivo/fashion?')
var colorCombinado = prompt('¿Qué color prefieres a la hora de combinar?')
var calzado = prompt('¿Prefieres sandalias, zapatillas ó tacones?')
var prendaInferior = prompt('¿Y entre la bermuda, el pantalon ó la falda cúal elegirías?')
var fiesta = prompt('¿Para una fiesta cual te gusta más, de vestido, chaqueta ó una combinación mixta?')
alert('Acompañanos '+nombre+' ¡Esta pagina te mostrara una parte de nuestros productos, no dejes de seguirnos!')
